/*
 * Copyright (c) 2016.
 */

package com.crooks;

import javax.persistence.*;

/**
 * Created by johncrooks on 6/21/16.
 */

@Entity         //required for it to be autogenerated with hibernate ORM
@Table(name = "users")    //User is used by PostGres and can't be used as a table name so we have to rename it so there are no conflicts
public class User {
    @Id                  //
    @GeneratedValue      //Auto generates the id
    int id;

    @Column(nullable = false)  //prevents columns from being empty and causing issues, won't allow the operation to occur
    String name;

    @Column(nullable = false)  //prevents columns from being empty and causing issues, won't allow the operation to occur
    String password;

    public User(String name, String password) {
        this.name = name;
        this.password = password;
    }

    public User() {
    }
}
